version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /home/node/app/node_modules
      - ~/project/s6/frontend:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ~/project/s6/frontend:/home/node/app
    command: ['npm', 'run', 'test']
